/// Flutter icons CCIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CCIcons
///      fonts:
///       - asset: fonts/CCIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CCIcons {
  CCIcons._();

  static const _kFontFam = 'CCIcons';
  static const String _kFontPkg = null;

  static const IconData allergyCustom = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData allergyEggs = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData allergyFish = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData allergySoybeans = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData allergyMilk = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData allergyPeanuts = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData allergyTreeNuts = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData allergyWheat = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData allergyShellfish = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
