#!/usr/bin/env node

var admin = require('firebase-admin')
var fs = require('fs')
var path = require('path')
var functions = require('firebase-functions')

var app = admin.initializeApp({
    credential: admin.credential.applicationDefault(),
    databaseURL: "https://chef-capp.firebaseio.com"
})

let db = admin.firestore();