#!/usr/bin/env python

import json
import sys

for fileName in sys.argv[1:]:
    id = 0
    wordList = {}
    with open(fileName) as f:
        for line in f:
            line = line[:-1]
            print (line)
            wordList[id] = line
            id += 1
        json_wordList = json.dumps(wordList, indent=4)
        print (wordList)


    fileName = fileName.rsplit('.', maxsplit=1)
    #print (fileName)
    fj = open(fileName[0] + '.json', "w+")
    fj.write(json_wordList)
    fj.close()

    #print (json_wordList)
